
x-kafka-common: &kafka-common
  image: confluentinc/cp-kafka:7.0.1
  environment:
    &kafka-common-env
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  restart: always
  depends_on:
    - zookeeper
  networks:
    - kafka-network

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "127.0.0.1:22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka1:
    <<: *kafka-common
    container_name: kafka-1
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092

  kafka2:
    <<: *kafka-common
    container_name: kafka-2
    ports:
      - "127.0.0.1:9093:9093"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://localhost:9093

  kafka3:
    <<: *kafka-common
    container_name: kafka-3
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://localhost:9094

  postgres:
    image: debezium/postgres:16
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./env.example
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./infra/postgres/replication_config.conf:/etc/postgresql/postgresql.conf
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: kafka-ui
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: zookeeper-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    restart: always
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-network

  schema-registry:
    image: bitnamilegacy/schema-registry:7.6
    container_name: schema-registry
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka1:19092,kafka2:19093,kafka3:19094
    networks:
      - kafka-network

  kafka-connect:
    build:
      context: ./infra/kafka-connect
    container_name: kafka-connect
    env_file:
      - env.example
    ports:
      - "8083:8083"
      - "9875:9875"
      - "9876:9876"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
      - postgres
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'kafka-connect'

      CONNECT_REST_ADVERTISED_HOST_NAME: 'localhost'

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 2
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 2
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 2

      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-config-storage'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offset-storage'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status-storage'

      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081/'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL:  'http://schema-registry:8081/'

      KAFKA_JMX_PORT: '9875'
      KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.15.0.jar=9876:/opt/kafka-connect.yml"

      CONNECT_CONFIG_PROVIDERS: "env"
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: "org.apache.kafka.common.config.provider.EnvVarConfigProvider"
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
    volumes:
      - ./infra/connectors/:/etc/kafka-connect/jars
    networks:
      - kafka-network

  init-kafka-connect:
    image: curlimages/curl:latest
    depends_on:
      - kafka-connect
    networks:
      - kafka-network
    command:
      - /bin/sh
      - -c
      - |
        until curl -s http://kafka-connect:8083/connectors > /dev/null 2>&1; do
          sleep 2
        done
        curl -i -X POST -H 'Content-Type: application/json' \
          http://kafka-connect:8083/connectors \
          -d @/tmp/pg-connector.json
        echo 'Connector registration complete!'
    volumes:
      - ./infra/kafka-connect/pg-connector.json:/tmp/pg-connector.json

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    links:
      - kafka-connect
    networks:
      - kafka-network

  grafana:
    build:
      context: ./infra/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - kafka-network

  data-writer:
    build:
      context: .
      dockerfile: infra/data_handler/Dockerfile
    container_name: data-writer
    depends_on: 
      init-kafka-connect:
        condition: service_completed_successfully
    env_file:
      - env.example
    networks:
      - kafka-network
    command: python ./app/main.py produce

  data-reader:
    build:
      context: .
      dockerfile: infra/data_handler/Dockerfile
    container_name: data-reader
    depends_on: 
      init-kafka-connect:
        condition: service_completed_successfully
    env_file:
      - env.example
    networks:
      - kafka-network
    command: python ./app/main.py consume

networks:
  kafka-network:
    driver: bridge
